framework:
    secret: '%env(APP_SECRET)%'
    router:
        utf8: true
    form:
        enabled: true
    csrf_protection: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    assets: true
    property_access: true
    property_info: true
    http_method_override: false

